services:
  papyrus:
    profiles: ["cli"]
    build: .
    environment:
      - OLLAMA_URL=${OLLAMA_URL:-http://ollama:11434}
      - OLLAMA_MODEL=${OLLAMA_MODEL:-qwen3:8b}
      - CUSTOM_PROMPT=${CUSTOM_PROMPT:-"Explain this document."}
      - PIPER_URL=${PIPER_URL:-http://piper:5000}
      - PDF_FILE=/${PDF_FILE:-pdfs/test.pdf}
    volumes:
      - ./pdfs:/pdfs:ro
      - ./voice:/app/voice
    command: []
    depends_on:
      - ollama

  ollama:
    build:
      context: .
      dockerfile: ollama.Dockerfile
    environment:
      - OLLAMA_MODEL=${OLLAMA_MODEL:-qwen3:8b}
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama

  piper:
    image: artibex/piper-http
    ports:
      - "5000:5000"
    environment:
      - MODEL_DOWNLOAD_LINK=${PIPER_VOICE_URL:-https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/lessac/medium/en_US-lessac-medium.onnx?download=true}
    volumes:
      - ./voice:/app/output
